spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    passeord:
  jpa:
    hibernate:
      ddl-auto:create
    h2:
      console:
        enable: true

fileRepositoryFolder: C:\\Users\\Utente\\Desktop\\fileRepositoryFolder
